 import '../models/card.dart';

List<CardModule> cardsList = const [
    CardModule(
      id: 1,
      price: 30,
      productImg: 'assets/images/img.jpg',
      productName: 'Boissons',
    ),
    CardModule(
      id: 2,
      price: 4.50,
      productImg: 'assets/images/img.jpg',
      productName: 'Fanta citron canette slim 25cl',
    ),
    CardModule(
      id: 3,
      price: 5.00,
      productImg: 'assets/images/img.jpg',
      productName: 'Fanta citron canette slim 33cl',
    ),
    CardModule(
      id: 4,
      price: 5.00,
      productImg: 'assets/images/img.jpg',
      productName: 'Hawaï tropical canette slim 25cl',
    ),
    CardModule(
      id: 5,
      price: 35.40,
      productImg: 'assets/images/img.jpg',
      productName: 'Pack Sidi Ali Eau minérale 6 x 1,5L',
    ),
    CardModule(
      id: 6,
      price: 34,
      productImg: 'assets/images/img.jpg',
      productName: 'Salim',
    ),
    CardModule(
      id: 7,
      price: 4.50,
      productImg: 'assets/images/img.jpg',
      productName: 'Fanta citron canette slim 25cl',
    ),
    CardModule(
      id: 8,
      price: 49.50,
      productImg: 'assets/images/img.jpg',
      productName: 'Oeufs',
    ),
    CardModule(
      id: 9,
      price: 70,
      productImg: 'assets/images/img.jpg',
      productName: 'luncheon',
    ),
    CardModule(
      id: 10,
      price: 4.50,
      productImg: 'assets/images/img.jpg',
      productName: 'Fanta orange canette slim 25cl',
    ),
    CardModule(
      id: 11,
      price: 3.95,
      productImg: 'assets/images/img.jpg',
      productName: '7 Up canette 33cl',
    ),
    CardModule(
      id: 12,
      price: 10.00,
      productImg: 'assets/images/img.jpg',
      productName: 'Lben beldi',
    ),
    CardModule(
      id: 13,
      price: 119.90,
      productImg: 'assets/images/img.jpg',
      productName: 'Fromage Edam boule',
    ),
    CardModule(
      id: 14,
      price: 68.95,
      productImg: 'assets/images/img.jpg',
      productName: 'Fromage fondu 64',
    ),
    CardModule(
      id: 15,
      price: 5.00,
      productImg: 'assets/images/img.jpg',
      productName: 'Mirinda orange canette 33cl',
    ),
    CardModule(
      id: 16,
      price: 17.95,
      productImg: 'assets/images/img.jpg',
      productName: 'Jambon de volaille',
    ),
    CardModule(
      id: 17,
      price: 11.50,
      productImg: 'assets/images/img.jpg',
      productName: 'Filet de dinde',
    ),
    CardModule(
      id: 18,
      price: 14.95,
      productImg: 'assets/images/img.jpg',
      productName: 'Champignons',
    ),
    CardModule(
      id: 19,
      price: 23.95,
      productImg: 'assets/images/img.jpg',
      productName: 'haricots_blancs.jpg',
    ),
    CardModule(
      id: 20,
      price: 80,
      productImg: 'assets/images/img.jpg',
      productName: 'Haricots rouges',
    ),
    CardModule(
      id: 21,
      price: 37.50,
      productImg: 'assets/images/img.jpg',
      productName: 'ZENTEK',
    ),
    CardModule(
      id: 22,
      price: 25.95,
      productImg: 'assets/images/img.jpg',
      productName: '10 sacs poubelle',
    ),
    CardModule(
      id: 23,
      price: 12.00,
      productImg: 'assets/images/img.jpg',
      productName: 'SELPAK',
    ),
    CardModule(
      id: 24,
      price: 21.95,
      productImg: 'assets/images/kasino.jpg',
      productName: 'CASINO',
    ),
    CardModule(
      id: 25,
      price: 20.95,
      productImg: 'assets/images/img.jpg',
      productName: 'FAIRY',
    ),
  ];